### ISSUE TITLE
빌드 시 config 관련 

### ISSUE THREAD

**Issue by SH5H** [velopert/learning-react#15]
17장 코드 스플리팅 부분에서 프로덕션 빌드를 할 때 생긴 문제 때문에  남깁니다.
윈도우즈를 사용하는지라 
16장 364페이지에서 
package.json  설정을
```"build" : "cross-env NODE_PATH=src react-scripts build", ```
이렇게 해준뒤에 계속 책을 보다가 
이 설정 그대로 빌드를 해보니

yarn run v1.9.4
$ cross-env NODE_PATH=src react-scripts build
'react-scripts'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn react-scripts ENOENT
    at notFoundError (C:\Users\seunghyunOh\Desktop\React\react-router-tutorial\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\seunghyunOh\Desktop\React\react-router-tutorial\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\seunghyunOh\Desktop\React\react-router-tutorial\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

이런 오류가 생겼습니다.
그래서 402 페이지에 빌드 과정을 보니
$ NODE_PATH=src node scripts/build.js 라고 되어있어

제 package.json도
```"build" : "cross-env NODE_PATH=src react-scripts build", ```
에서 

``` "build": "cross-env NODE_PATH=src node scripts/build.js",```

이렇게 수정한 뒤에 빌드를 했더니 되네요

**Comment by SH5H** [comment]
추가적으로 궁금한건데 빌드된 파일을 실행시키고개발자 콘솔에서 vendor.js 파일 크기를 볼려는데
size에 (from ServiceWorker)이렇게 적혀있고 size가 안나오네요 왜 이러죠?

**Comment by velopert** [comment]
감사합니다. 반영하겠습니다.

이 부분은 2쇄 때 전체적으로 수정이 될 부분인데, NODE_PATH 를 따로 설정하지 않고, .env 파일을 루트경로로 만들어서 NODE_PATH=src 라고 적어도 똑같이 작동합니다.

20.1.5.1 에서도 이와 같은 방식으로 진행합니다.

NODE_PATH 를 명령어로 따로 설정해주면 yarn eject 하게 됐을 때 따로 코드를 수정해줘야하는 단점이 있습니다.

캐시를 날리고 작업해보시거나, index.js 에서 registerServiceWorker(); 를 주석처리해보시면 됩니다.
