### ISSUE TITLE
p.554 node scripts/build.server.js 실행 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by wjdekdnlt** [velopert/learning-react#275]
앞의 부분에서 webpack.config.server.js와 build.server.js를 책에 나온대로 
$ node scripts/build.server.js
$ node scripts/webpack.config.server.js를 실행하면 오류가 발생합니다.
$ node config/build.server.js
```
C:\Users\user\ssr-recipe\config\env.js:12
  throw new Error(
  ^

Error: The NODE_ENV environment variable is required but was not specified.
    at Object.<anonymous> (C:\Users\user\ssr-recipe\config\env.js:12:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\user\ssr-recipe\config\webpack.config.server.js:5:30)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```
벨로퍼티님이 깃허브에 올리신 webpack.config.server.js파일과 build.server.js파일을 복붙해서 해봐도 같은 오류가 발생합니다. 뭐가 문제일까요?

**Comment by wjdekdnlt** [comment]
다음과 같은 에러도 발생합니다.
```
$ node scripts/build.server.js
C:\Users\user\ssr-recipe\config\webpack.config.server.js:12
const publicUrl = paths.servedPath.slice(0, -1);
```

**Comment by velopert** [comment]
이번 주말에 확인해보겠습니다!

**Comment by DJ-Yang** [comment]
#259 2번째 에러는 다음과 같이 해결하면 된다고 하네요!

**Comment by velopert** [comment]
1번째 오류는 build.server.js 에서 NODE_ENV 설정이 안됐을때 발생하는 에러인데요 2번째 에러가 나타난 것으로 봐서 해당 부분은 해결 한 것으로 예상됩니다.

2번째 에러 관련하여 corrections.md 에 추가했습니다.
https://github.com/velopert/learning-react/blob/master/corrections.md
