### ISSUE TITLE
개정판 23 회원가입 api 질문드립니다.

### ISSUE THREAD

**Issue by kkwoncokr** [velopert/learning-react#301]
/api/auth/auth.ctrl.js

`export const register = async ctx => {
  // 회원가입
  const schema = Joi.object().keys({
    username: Joi.string()
      .alphanum()
      .min(3)
      .max(20)
      .required(),
    password: Joi.string().required(),
  });
  const result = schema.validate(ctx.request.body);
  if (result.error) {
    ctx.status = 400;
    ctx.body = result.error;
    return;
  }

  const { username, password } = ctx.request.body;
  try {
    // username  이 이미 존재하는지 확인
    const exists = await User.findByUsername(username);
    if (exists) {
      ctx.status = 409; // Conflict
      return;
    }

    const user = new User({
      username,
    });
    await user.setPassword(password); // 비밀번호 설정
    await user.save(); // 데이터베이스에 저장

    ctx.body = user.serialize();
  } catch (e) {
    ctx.throw(500, e);
  }
};`
models/user.js

`import mongoose from 'mongoose';
import bcrypt from 'bcrypt';

const { Schema } = mongoose;

const UserSchema = new Schema({
  username: String,
  hashedPassword: String,
});

UserSchema.method.setPassword = async function(password) {
  const hash = await bcrypt.hash(password, 10);
  this.hashedPassword = hash;
};

UserSchema.method.checkPassword = async function(password) {
  const result = await bcrypt.compare(password, this.hashedPassword);
  return result;
};

UserSchema.statics.findByUsername = function(username) {
  return this.findOne({ username });
};

UserSchema.method.serialize = function() {
    const data = this.toJSON();
    delete data.hashedPassword;
    return data;
}

const User = mongoose.model('User', UserSchema);

export default User;
`

이렇게 작성하였는데,

  TypeError: user.setPassword is not a function
      at register (file:///Users/kang_kyoungwon/myspace/koa/koa_backend/src/api/auth/auth.ctrl.js:33:16)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async bodyParser (/Users/kang_kyoungwon/myspace/koa/koa_backend/node_modules/koa-bodyparser/index.js:95:5)

회원가입시 해당 오류가 발생합니다.

어떠한 이유 때문일까요?

**Comment by kkwoncokr** [comment]
> /api/auth/auth.ctrl.js
> 
> `export const register = async ctx => {
> // 회원가입
> const schema = Joi.object().keys({
> username: Joi.string()
> .alphanum()
> .min(3)
> .max(20)
> .required(),
> password: Joi.string().required(),
> });
> const result = schema.validate(ctx.request.body);
> if (result.error) {
> ctx.status = 400;
> ctx.body = result.error;
> return;
> }
> 
> const { username, password } = ctx.request.body;
> try {
> // username 이 이미 존재하는지 확인
> const exists = await User.findByUsername(username);
> if (exists) {
> ctx.status = 409; // Conflict
> return;
> }
> 
> ```
> const user = new User({
>   username,
> });
> await user.setPassword(password); // 비밀번호 설정
> await user.save(); // 데이터베이스에 저장
> 
> ctx.body = user.serialize();
> ```
> 
> } catch (e) {
> ctx.throw(500, e);
> }
> };`
> models/user.js
> 
> `import mongoose from 'mongoose';
> import bcrypt from 'bcrypt';
> 
> const { Schema } = mongoose;
> 
> const UserSchema = new Schema({
> username: String,
> hashedPassword: String,
> });
> 
> UserSchema.method.setPassword = async function(password) {
> const hash = await bcrypt.hash(password, 10);
> this.hashedPassword = hash;
> };
> 
> UserSchema.method.checkPassword = async function(password) {
> const result = await bcrypt.compare(password, this.hashedPassword);
> return result;
> };
> 
> UserSchema.statics.findByUsername = function(username) {
> return this.findOne({ username });
> };
> 
> UserSchema.method.serialize = function() {
> const data = this.toJSON();
> delete data.hashedPassword;
> return data;
> }
> 
> const User = mongoose.model('User', UserSchema);
> 
> export default User;
> `
> 
> 이렇게 작성하였는데,
> 
> TypeError: user.setPassword is not a function
> at register (file:///Users/kang_kyoungwon/myspace/koa/koa_backend/src/api/auth/auth.ctrl.js:33:16)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async bodyParser (/Users/kang_kyoungwon/myspace/koa/koa_backend/node_modules/koa-bodyparser/index.js:95:5)
> 
> 회원가입시 해당 오류가 발생합니다.
> 
> 어떠한 이유 때문일까요?
