### ISSUE TITLE
개정판 챕터 20.3.4 express를 이용한 ssr 예제를 빌드한 dist/server.js 실행시 에러

### ISSUE THREAD

**Issue by passedball** [velopert/learning-react#307]
개정판 챕터 20.3.4 express를 이용한 예제 소스코드를 빌드해 dist/server.js를 생성하는 데까지 따라왔습니다. (page. 555)
그런데 dist/server.js를 실행하면 에러가 발생합니다.
스스로 해결해보려고 시도하다가 답이 안 보여 도움을 구합니다.
npm run start:server 를 실행하면 아래와 같은 에러를 내보냅니다.

`TypeError: Object(...) is not a function
    at Object.<anonymous> (C:\work\ssr-recipe\dist\server.js:1:1184)
    at n (C:\work\ssr-recipe\dist\server.js:1:110)
    at Module.<anonymous> (C:\work\ssr-recipe\dist\server.js:1:2049)
    at n (C:\work\ssr-recipe\dist\server.js:1:110)
    at C:\work\ssr-recipe\dist\server.js:1:903
    at Object.<anonymous> (C:\work\ssr-recipe\dist\server.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssr-recipe@0.1.0 start:server: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ssr-recipe@0.1.0 start:server script.`

![npm-run-start-server](https://user-images.githubusercontent.com/65770332/102297189-285eab00-3f92-11eb-9f6b-ae8607257899.png)

**Comment by passedball** [comment]
해결했습니다. 
웹팩 설정, exporLocals: true 에 문제가 있었습니다.
아래처럼 수정해야 합니다.

`modules: { exportOnlyLocals: true }`
