### ISSUE TITLE
개정판 20.4.3 PreloadContext 만들기 예제를 빌드 후 실행하면 에러가 납니다.

### ISSUE THREAD

**Issue by passedball** [velopert/learning-react#308]
책에 있는 예제와 다르게 한 부분은 없는데 서버를 실행하면 에러가 떨어집니다.
어디가 잘못 됐을까요??
에러 내용은 이렇습니다.
`
TypeError: r.mark is not a function
    at C:\work\ssr-recipe\dist\server.js:1:5661
    at Module.<anonymous> (C:\work\ssr-recipe\dist\server.js:1:6479)
    at n (C:\work\ssr-recipe\dist\server.js:1:110)
    at C:\work\ssr-recipe\dist\server.js:1:903
    at Object.<anonymous> (C:\work\ssr-recipe\dist\server.js:1:913)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssr-recipe@0.1.0 start:server: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ssr-recipe@0.1.0 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
![npm-run-start-server](https://user-images.githubusercontent.com/65770332/102344753-b745e480-3fdf-11eb-96dd-3ee90f0ae1fa.png)
`

**Comment by velopert** [comment]
해당 프로젝트 github에 올려주시고 주소 알려주시면 제가 한 번 확인해볼게요!
