### ISSUE TITLE
개정판 20.7.3  556페이지 yarn start:server 에러

### ISSUE THREAD

**Issue by kimyoungjae96** [velopert/learning-react#309]
yarn start:server                                                                                                            ok | 15.4.0 node | 18:04:27 
yarn run v1.22.10
$ node dist/server.js
node:internal/modules/cjs/loader:1125
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/crerar/Desktop/github/js-study/09/manage-react/node_modules/@babel/runtime/helpers/esm/arrayWithHoles.js
require() of ES modules is not supported.
require() of /Users/crerar/Desktop/github/js-study/09/manage-react/node_modules/@babel/runtime/helpers/esm/arrayWithHoles.js from /Users/crerar/Desktop/github/js-study/09/manage-react/dist/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename arrayWithHoles.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/crerar/Desktop/github/js-study/09/manage-react/node_modules/@babel/runtime/helpers/esm/package.json.

    at new NodeError (node:internal/errors:278:15)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/crerar/Desktop/github/js-study/09/manage-react/dist/server.js:1:1504)
    at t (/Users/crerar/Desktop/github/js-study/09/manage-react/dist/server.js:1:110)
    at Module.<anonymous> (/Users/crerar/Desktop/github/js-study/09/manage-react/dist/server.js:1:2862)
    at t (/Users/crerar/Desktop/github/js-study/09/manage-react/dist/server.js:1:110) {
  code: 'ERR_REQUIRE_ESM'
}

yarn start:build는 성공했는데 yarn start:server를 한 순간 다음과 같은 에러가 뜹니다!

노드 버전은 15.4, 12.16.2로 둘다 해보았지만 안되었습니다.

**Comment by kimyoungjae96** [comment]
기존에 있던 디렉토리에 하다보니 파일이 꼬인 것 같습니다... !! 새로 프로젝트를 만들어서 하니 해결이 되었습니다.
