### ISSUE TITLE
20장 서버사이드 렌더링 redux-saga

### ISSUE THREAD

**Issue by yoonminsang** [velopert/learning-react#316]
여기서 계속 code: 'ERR_REQUIRE_ESM' 이 오류가 뜹니다.
해결하려고 이것저것해봤는데 안되네요 뭐가 문제일까요??

**Comment by yoonminsang** [comment]
원본 코드랑 비교해서 찾았습니다.
webpack.config.server.js 파일의 코드가 잘못되었네요
원본코드
  externals: [
    nodeExternals({
      allowlist: [/@babel/],
    }),
  ],
책
  externals: [nodeExternals()],

**Comment by yoonminsang** [comment]
http://localhost:5000/users 를 들어가면 아래 오류가 뜹니다.
/, /red, /blue는 정상적으로 작동합니다. return값이 없다는것같은데 뭐가 문젠지 모르겠습니다.

(node:17468) UnhandledPromiseRejectionWarning: Error: S(...): Nothing was returned from render. 
This usually means a return statement is missing. Or, to render nothing, return null.
    at validateRenderResult (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:3250:15)
    at processChild (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:3374:9)
    at resolve (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at C:\Users\User\Desktop\redagi\ssr-recipe\dist\server.js:1:6059
    at tryCatch (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\User\Desktop\redagi\ssr-recipe\node_modules\regenerator-runtime\runtime.js:118:21)

**Comment by velopert** [comment]
5쇄때 수정됐습니다 :D

https://github.com/velopert/learning-react/blob/master/_old_corrections/%EA%B0%9C%EC%A0%95%ED%8C%90-4%EC%87%84.md#20302-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-pg552
