### ISSUE TITLE
P.577 start:server시 esm 관련 오류 발생

### ISSUE THREAD

**Issue by SoyaNyan** [velopert/learning-react#331]
20.4.4의 서버에서 리덕스 설정 및 PreloadContext 사용하기 실습에서 P.576까지 코드 작성을 마치고
yarn build
yarn build:server
까지는 문제 없이 진행되고 yarn start도 이상이 없습니다.
다만 yarn start:server로 서버를 실행하려 하면 다음과 같은 오류가 발생합니다.

`node:internal/modules/cjs/loader:1109
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^
      Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\nodeapps\react-ex\ssr-recipe\node_modules\@babel\runtime\helpers\esm\defineProperty.js 
      require() of ES modules is not supported.
      require() of C:\nodeapps\react-ex\ssr-recipe\node_modules\@babel\runtime\helpers\esm\defineProperty.js from C:\nodeapps\react-ex\ssr-recipe\dist\server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
      Instead rename defineProperty.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\nodeapps\react-ex\ssr-recipe\node_modules\@babel\runtime\helpers\esm\package.json.
    at new NodeError (node:internal/errors:329:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1109:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\nodeapps\react-ex\ssr-recipe\dist\server.js:1:1349)        
    at t (C:\nodeapps\react-ex\ssr-recipe\dist\server.js:1:110)
    at Module.<anonymous> (C:\nodeapps\react-ex\ssr-recipe\dist\server.js:1:2802)        
    at t (C:\nodeapps\react-ex\ssr-recipe\dist\server.js:1:110) {
	    code: 'ERR_REQUIRE_ESM'
	}
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

해결 방법이 있을까요?

**Comment by SoyaNyan** [comment]
이슈 [#316](https://github.com/velopert/learning-react/issues/316) 과 동일한 수정으로 start:server 가능했습니다.
