### ISSUE TITLE
create-react-app 업데이트에 따른 변화/오탈자?

### ISSUE THREAD

**Issue by WDever** [velopert/learning-react#42]
컴포넌트 스타일링 챕터 진행중 sass-loader 설정에서 막혔습니다

@import를 이용해서 더 쉽게 scss 파일을 불러오게 하는건데, config/webpack.config.dev.js에 scss-loader 부분이 없네요

그리고 176p의 마지막 예제에 경로가 config.paths.js로 되어있습니다 config/paths.js가 맞을것 같아요

**Comment by velopert** [comment]
https://github.com/velopert/learning-react#%EC%9D%BD%EC%96%B4%EC%A3%BC%EC%84%B8%EC%9A%94

우선 책을 전체적으로 업데이트 할 때 까지는 이전 버전을 사용하시는게 좋을 것 같습니다.
176p 오탈자 반영하고 이슈 닫을게요~

**Comment by velopert** [comment]
추가적으로 scss-loader 말고 sass-loader 를 찾아보시면 있을거에요

          {
            test: sassRegex,
            exclude: sassModuleRegex,
            use: getStyleLoaders({ importLoaders: 2 }, 'sass-loader'),
          },

최근 CRA 에서는 'sass-loader'  자리에 객체 형태로 옵션을 그대로 넣으면 될지는..  모르겠지만 조만간 해보고 회신드리겠습니다.

**Comment by EKAR0N** [comment]
아 감사합니다! 한번 해볼게용!

**Comment by EKAR0N** [comment]
{
            test: sassRegex,
            exclude: sassModuleRegex,
            use: getStyleLoaders({ importLoaders: 2 }, 'sass-loader', { includePaths: paths.styles }),
          },
이렇게 해봤는데 안되네요 ㅠㅠ 이게 아닌감...

**Comment by EKAR0N** [comment]
@velopert 
이것때메 며칠째 진도를 못나가는데요 ㅠㅠ

주신 링크에 있는대로 다시 프로젝트 만들어서 eject 하고 yarn start 하면
yarn start
yarn run v1.10.1
$ node scripts/start.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'babel-loader'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/mnt/d/styling-react/config/webpack.config.dev.js:145:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/d/styling-react/scripts/start.js:31:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

이런 에러가 납니다..

babel-loader 에러인것 같은데 흐흐흑.. 어찌해야 하나요

아무것도 안건들고 yarn eject만 하고 yarn start하면 걸립니다 ㅠㅠ

**Comment by velopert** [comment]
```
$ yarn eject
$ yarn install
```

eject 후 yarn install 을 한번 더 입력하여 모듈들을 다시 제대로 설치하세요.
CRA 쪽에도 문의 해봤는데 yarn 쪽 버그라고하네요...!

**Comment by EKAR0N** [comment]
윽... 그런거였군요 ㅠㅠㅠ 감사합니당

**Comment by YouDuk** [comment]
```$ create-react-app sample-project --scripts-version=1.1.5```
위의 커맨드로 프로젝트를 생성해도  yarn eject해보니 웹팩 설정은 최신 CRA를 따라가는 것 같네요. 때문에 책에 나온 코드 형식과 완전히 달라집니다 ㅠㅠ 저도 해보면서 해결 방법을 찾으면 코드 올리겠습니다.

**Comment by YouDuk** [comment]
@velopert 앗 벨로퍼트님이 알아봐주셨네요. 네, 다시 확인해보겠습니다 :-)

**Comment by YouDuk** [comment]
@velopert `npx`를 붙이니 잘 되네요^^;;

**Comment by innocarpe** [comment]
책과 이 `@import 'utils';` 를 붙이는 방식으로 하려면

```diff
options: {
  includePaths: [paths.appSrc + '/styles'],
-  data: `@import 'utils';`
}
```

와 같이 해도 되는군요. 좋은 정보 감사합니다.

**Comment by lshwa80** [comment]
현재 "리액트를 다루는 기술" 을 항상 참고하며,
리덕스 기반으로 리액트 프로젝트를 진행하고 있습니다.
create-react-app 이 계속 업데이트 되면서,
기본 src 기본 경로도 jsconfig.json 이나 tsconfig.json 파일에 선언을 통해 활용하고 있는데요.
npx create-react-app 을 설치하고 위에 설명해 주신데로
webpack 설정 파일에 style 경로를 맞춰도 에러가 나네요..ㅠ
버전업된 기반으로 블로그 업데이트는 언제쯤 되는지 궁금합니다.
책에 나온 내용처럼 버전에 맞는 webpack 코드 스플리팅 및 버전이 바뀌면서 실행되지 않는 내용들을.. 
간절히 기다리고 있습니다.ㅠ
또 개인적으로는 next.js + typescript + react/redux 활용으로 redux-pender 를 활용한 약간은 api 연동까지 깊이있는 내용도 있었으면 좋겠습니다~

위에 제시한 style 경로 설정 이라도 확인 되었으면 좋겠습니다.
